version: 2

jobs:
  # Branch Jobs
  build-branch:
    machine: true
    steps:
      - checkout
      - run: docker login $DOCKER_SERVER -u $DOCKER_USER -p $DOCKER_PASS
      # Build the application image.
      - run: docker build -t $DOCKER_SERVER/defrostedtuna/uptilt-weather:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7) .
      # Upload the image to the registry.
      - run: docker push $DOCKER_SERVER/defrostedtuna/uptilt-weather:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)

  # Tag Jobs
  build-tag:
    machine: true
    steps:
      - checkout
      - run: docker login $DOCKER_SERVER -u $DOCKER_USER -p $DOCKER_PASS
      # Build the application image.
      - run: docker build -t $DOCKER_SERVER/defrostedtuna/uptilt-weather:$CIRCLE_TAG .
      # Upload the image to the registry.
      - run: docker push $DOCKER_SERVER/defrostedtuna/uptilt-weather:$CIRCLE_TAG

workflows:
  version: 2

  build-branch:
    jobs:
      - build-branch:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  build-tag:
    jobs:
      - build-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/